sudo: false
language: rust
rust:
- 1.22.0  # Oldest supported version
- stable
- beta
- nightly
matrix:
  include:
  - env: RUSTFMT
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt-preview
    script:
      - cargo fmt -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests
  - env: CLIPPY_VERSION="0.0.209"
    rust: nightly-2018-06-19
    install:
      - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
      - cargo clippy --features "cli serde_yaml serde_json" -- -D clippy

env:
  global:
  - COVERALLS=0.0.6
  - WHEN=0.1.0
  - secure: FGosPYxgSM1Csyy2q/OiSW2KA7IDlIlLTODxwgszP/MIwOIMobAs5f+IqrEngEi3zKa0IPahQ3DZMZFAaNw9e1gI90ZQKpYgDQHNPeCtO0q4OV94RAjAFqhqVPxXwmNug88tm3NMokzzOafosWD8AzL7dYAx63KBpgCNZteW6CM=

install:
- rustc -Vv
- cargo -V
- which cargo-coveralls || travis_wait cargo install cargo-travis --force --vers $COVERALLS
- if [[ `cargo-when --version` != *$WHEN ]] ; then travis_wait cargo install cargo-when --force --vers $WHEN; fi
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo check --verbose --no-default-features
- cargo check --verbose --features "cli serde_json object_sorted"
- rm -rf target/debug/deps/*liquid*  # Avoid skeptic problems
- cargo test  --verbose --features "cli serde_json"
- cargo when --channel nightly bench --features "cli serde_json"
- cargo when --channel stable doc --no-deps --all-features

after_success:
- cargo when --channel stable coveralls

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

addons:
  apt:
    packages:
    # necessary for `cargo coveralls`
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
