install:
  - echo Do Nothing

test_script:
  - echo Do Nothing

branches:
  only:
  # Release tags
  - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
