[workspace]
members = [
  "liquid-error",
  "liquid-value",
  "liquid-compiler",
  "liquid-interpreter",
  "liquid-derive",
  "liquid-help-md",
  "liquid-bin",
]

[package]
name = "liquid"
version = "0.19.0"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://docs.rs/liquid"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"

[badges]
azure-devops = { project = "cobalt-org", pipeline = "liquid-rust" }

[features]
default = ["extra-filters", "serde"]
extra-filters = []
# Ensure keys in `Value`s `Object`s to be sorted.
object_sorted = []
jekyll-filters = []

[dependencies]
regex = "1.0"
lazy_static = "1.0"
chrono = "0.4"
unicode-segmentation = "1.2"
itertools = "0.8.0"
url = "1.5"
doc-comment = "0.3"
liquid-error = { version = "^0.19", path = "liquid-error" }
liquid-value = { version = "^0.19", path = "liquid-value" }
liquid-compiler = { version = "^0.19", path = "liquid-compiler" }
liquid-interpreter = { version = "^0.19", path = "liquid-interpreter" }
liquid-derive = { version = "^0.19", path = "liquid-derive" }

serde = { version = "1.0", optional = true, features = ["derive"] }
deunicode = "1.0.0"

[dev-dependencies]
difference = "2.0"
serde_yaml = "0.8"
tera = "0.11"
handlebars = "2.0"
serde_derive = "1.0"
serde_json = "1.0"
