[workspace]
members = [
  "crates/error",
  "crates/value",
  "crates/compiler",
  "crates/interpreter",
  "crates/derive",
  "crates/core",
  "crates/help-md",
  "crates/bin",
  "crates/kstring",
]

[package]
name = "liquid"
version = "0.19.0"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://docs.rs/liquid"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"
edition = "2018"

[badges]
azure-devops = { project = "cobalt-org", pipeline = "liquid-rust" }

[features]
default = ["extra-filters", "serde"]
extra-filters = []
# Ensure keys in `Value`s `Object`s to be sorted.
object_sorted = []
jekyll-filters = []

[dependencies]
regex = "1.0"
once_cell = "1.0"
chrono = "0.4"
unicode-segmentation = "1.2"
itertools = "0.8.0"
url = "1.5"
doc-comment = "0.3"
kstring = { version = "0.1.0", path = "crates/kstring" }
liquid-core = { version = "^0.19", path = "crates/core" }
liquid-derive = { version = "^0.19", path = "crates/derive" }

serde = { version = "1.0", optional = true, features = ["derive"] }
deunicode = "1.0.0"

[dev-dependencies]
difference = "2.0"
serde_yaml = "0.8"
tera = "0.11"
handlebars = "3.0"
serde_derive = "1.0"
serde_json = "1.0"
