[workspace]
members = [
  "crates/derive",
  "crates/core",
  "crates/help-md",
  "crates/bin",
  "crates/lib",
]

[package]
name = "liquid"
version = "0.21.5"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://docs.rs/liquid"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"
edition = "2018"

[badges]
azure-devops = { project = "cobalt-org", pipeline = "liquid-rust" }

[features]
default = ["stdlib"]
stdlib = ["liquid-lib/stdlib"]

[dependencies]
doc-comment = "0.3"
kstring = "1.0"
liquid-core = { version = "^0.21.0", path = "crates/core" }
liquid-derive = { version = "^0.22.0", path = "crates/derive" }
liquid-lib = { version = "^0.21.0", path = "crates/lib", optional = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
difference = "2.0"
serde_yaml = "0.8"
tera = "1.0"
handlebars = "3.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1.0"
criterion = "0.3"

[[bench]]
name = "liquid"
harness = false

[[bench]]
name = "handlebars"
harness = false

[[bench]]
name = "tera_bigcontext"
harness = false

[[bench]]
name = "tera_template"
harness = false

[[bench]]
name = "tera_tera"
harness = false
