[package]
name = "liquid-derive"
version = "0.22.0"
authors = ["Pedro Gonçalo Correia <goncalerta@gmail.com>"]
description = "The liquid templating language for Rust"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[badges]
azure-devops = { project = "cobalt-org", pipeline = "liquid-rust" }

[dependencies]
syn = "1.0"
proc-quote = "0.3"
proc-macro2 = "1.0"
